#!/usr/bin/env python3

import os
import sys

# set server timezone in UTC before time module imported
__import__('os').environ['TZ'] = 'UTC'

LIB_PATH = os.path.join(os.path.split(os.path.realpath(__file__))[0], '..', '..', 'odoo-src', 'dy-odoo')
sys.path.append(LIB_PATH)

import odoo
from core import init_patch

if __name__ == "__main__":
    init_patch()

    odoo.modules.module.load_openerp_module('web')

    from core import patch
    patch.monkey_patch()

    odoo.cli.main()
